# Generated by Django 5.0 on 2024-04-04 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Myreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('driveDate', models.DateField(null=True)),
                ('link', models.URLField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'placement',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcode', models.CharField(max_length=12, null=True)),
                ('dob', models.DateField(null=True)),
                ('CollegeName', models.CharField(max_length=250, null=True)),
                ('Department', models.CharField(max_length=50, null=True)),
                ('ContactNo', models.CharField(max_length=12, null=True)),
                ('SSCMarks', models.FloatField(max_length=10, null=True)),
                ('YPone', models.CharField(max_length=5, null=True)),
                ('SwD', models.FloatField(max_length=10, null=True)),
                ('YOP2', models.CharField(max_length=5, null=True)),
                ('BEMarks', models.FloatField(max_length=10, null=True)),
                ('YOP3', models.CharField(max_length=5, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied', models.CharField(max_length=150, null=True)),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studsignup.userdetails')),
            ],
        ),
    ]
