# Generated by Django 5.0 on 2024-04-06 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studsignup', '0002_uploadedexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedexcel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='studsignup.myreg'),
        ),
    ]
