# Generated by Django 5.0 on 2024-04-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studsignup', '0004_companydetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyDetails',
        ),
    ]
