# Generated by Django 5.0 on 2024-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studsignup', '0005_delete_companydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreg',
            name='jobDescription',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='myreg',
            name='jobRole',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myreg',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myreg',
            name='package',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
