# Generated by Django 5.0 on 2024-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studsignup', '0007_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='text',
        ),
        migrations.AddField(
            model_name='notice',
            name='comname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='rounds',
            field=models.TextField(null=True),
        ),
    ]
