# Generated by Django 5.0 on 2024-04-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studsignup', '0008_remove_notice_text_notice_comname_notice_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
